name: 'type-check'
description: 'Check code type'
runs:
  using: 'composite'
  steps:
    - uses: actions/checkout@v2
    - uses: actions/cache@v2
      with:
        path: node_modules
        key: yarn-packages-v0-${{ hashFiles('**/yarn.lock') }}
        restore-keys: |
          yarn-packages-v0-
    - uses: actions/setup-node@v2
      with:
        node-version: '16'
    - run: yarn type-check
      shell: bash
