name: created-pr

on: pull_request

jobs:
  install-deps:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/cache@v2
        with:
          path: node_modules
          key: yarn-packages-v0-{{ hashFiles('**/yarn.lock') }}
          restore-keys: |
            yarn-packages-v0-
      - uses: actions/setup-node@v2
        with:
          node-version: '16'
      - name: Install Dependencies
        run: yarn --frozen-lockfile
  lint:
    runs-on: ubuntu-latest
    needs:
      - install-deps
    steps:
      - uses: actions/checkout@v2
      - uses: actions/cache@v2
        with:
          path: node_modules
          key: yarn-packages-v0-{{ hashFiles('**/yarn.lock') }}
          restore-keys: |
            yarn-packages-v0-
      - uses: actions/setup-node@v2
        with:
          node-version: '16'
      - run: yarn --frozen-lockfile
      - run: yarn lint
  type-check:
    runs-on: ubuntu-latest
    needs:
      - install-deps
    steps:
      - uses: actions/checkout@v2
      - uses: actions/cache@v2
        with:
          path: node_modules
          key: yarn-packages-v0-{{ hashFiles('**/yarn.lock') }}
          restore-keys: |
            yarn-packages-v0-
      - uses: actions/setup-node@v2
        with:
          node-version: '16'
      - run: yarn --frozen-lockfile
      - run: yarn type-check
  build-app:
    runs-on: ubuntu-latest
    needs:
      - lint
      - type-check
    steps:
      - uses: actions/checkout@v2
      - uses: actions/cache@v2
        with:
          path: node_modules
          key: yarn-packages-v0-{{ hashFiles('**/yarn.lock') }}
          restore-keys: |
            yarn-packages-v0-
      - uses: actions/setup-node@v2
        with:
          node-version: '16'
      - run: yarn --frozen-lockfile
      - uses: actions/cache@v2
        with:
          path: .next/cache
          key: nextjs-build-cache-v0-${{ hashFiles('**/yarn.lock') }}
          restore-keys: |
            nextjs-build-cache-v0-
      - run: yarn build
