name: created-pr

on: pull_request

jobs:
  install-deps:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: install-deps
        uses: ./github/actions/install-deps
  lint:
    runs-on: ubuntu-latest
    needs:
      - install-deps
    steps:
      - uses: actions/checkout@v2
      - name: lint
        uses: ./github/actions/lint
  type-check:
    runs-on: ubuntu-latest
    needs:
      - install-deps
    steps:
      - uses: actions/checkout@v2
      - name: type-check
        uses: ./github/actions/type-check
  build-app:
    runs-on: ubuntu-latest
    needs:
      - lint
      - type-check
    steps:
      - uses: actions/checkout@v2
      - name: build-app
        uses: ./.github/actions/build-app
