name: created-pr

on: pull_request

jobs:
  install-deps:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          node-version: '14'
          cache: 'yarn'
      - run: yarn install
      - name: Install Dependencies
        run: yarn --frozen-lockfile
  lint:
    runs-on: ubuntu-latest
    needs:
      - install-deps
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          node-version: '14'
          cache: 'yarn'
      - run: yarn lint
  type-check:
    runs-on: ubuntu-latest
    needs:
      - install-deps
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          node-version: '14'
          cache: 'yarn'
      - run: yarn type-check
  build-app:
    runs-on: ubuntu-latest
    needs:
      - lint
      - type-check
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          node-version: '14'
          cache: 'yarn'
      - run: yarn build
